version: '3.8'

services:
  app:
    build: .
    container_name: laravel_sqlite_app
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
